version: 2

models:
  - name: stg_asset_status_history
    description: "stg層。RAW層で外部テーブルのアセットステータス変更履歴について型など変換している。"
    columns:
      - name: event_time_jst
        description: "ステータス変更日時(JST)"
        tests:
          - not_null
          # - is_datetime
      - name: ticker
        description: "ticker名"
        tests:
          - not_null
      - name: is_monitor
        description: "モニタリング対象フラグ"
        tests:
          - not_null
      - name: is_watch
        description: "取引対象フラグ"
        tests:
          - not_null

  - name: stg_trade_history
    description: "stg層。RAW層で外部テーブルの取引履歴について型など変換している。"
    columns:
      - name: event_time_jst
        description: "レコード入力日時(JST)"
        tests:
          - not_null
          # - is_datetime
      - name: trade_date
        description: "取引日(JST)"
        tests:
          - not_null
      - name: ticker
        description: "ticker名"
        tests:
          - not_null
      - name: trade_type
        description: "取引種別(buy or sell)"
        tests:
          - not_null
      - name: account
        description: "口座名(gp_fund,yuitomaru..)"
        tests:
          - not_null
      - name: order_count
        description: "取引口数"
        tests:
          - not_null
      - name: price
        description: "取引価格"
        tests:
          - not_null
      - name: memo
        description: "メモ"

  - name: stg_price_data
    description: "stg層。GCSからData Transferで定期的にインポートされる価格データについて型など変換している。同一データが重複している可能性あり。"
    columns:
      - name: base_date
        description: "価格基準日"
        tests:
          - not_null
      - name: ticker
        description: "ticker名"
        tests:
          - not_null
      - name: ohlc_type
        description: "価格種別(Open/High/Low/Close)"
        tests:
          - not_null
      - name: price
        description: "価格"
        # tests:
          # - not_null -- nullもありえる(ex. 指数のHigh/Low)
      - name: fetch_time_jst
        description: "データ取得日時(JST)"
        tests:
          - not_null

  - name: stg_entry_point
    description: "stg層。RAW層で外部テーブルのエントリー水準について型など変換している。"
    columns:
      - name: add_date
        description: "エントリー水準登録日"
      - name: ticker
        description: "ticker名"
        tests:
          - not_null
      - name: entry_price
        description: "エントリー水準価格"
        tests:
          - not_null
      - name: memo
        description: "メモ"