version: 2

models:
  - name: dwh_trade_history_with_cash
    description: "DWH層。各取引の裏のcashの移動レコードも含めた取引履歴。"
    columns:
      - name: event_time_jst
        description: "レコード入力日時(JST)"
        tests:
          - not_null
          # - is_datetime
      - name: trade_date
        description: "取引日(JST)"
        tests:
          - not_null
      - name: ticker
        description: "ticker名"
        tests:
          - not_null
      - name: trade_type
        description: "取引種別(buy or sell)"
        tests:
          - not_null
      - name: account
        description: "口座名(gp_fund,yuitomaru..)"
        tests:
          - not_null
      - name: order_count
        description: "取引口数"
        tests:
          - not_null
      - name: price
        description: "取引価格"
        tests:
          - not_null
      - name: memo
        description: "メモ"

  - name: dwh_asset_master
    description: "DWH層。アセットマスタ"
    columns:
      - name: ticker
        description: "ticker名"
        tests:
          - not_null
      - name: asset_name
        description: "アセット名"
        tests:
          - not_null
      - name: asset_type
        description: "アセット種別(株,金利..)"
        tests:
          - not_null
      - name: is_monitor
        description: "モニタリング対象フラグ"
        tests:
          - not_null
      - name: is_watch
        description: "取引対象フラグ"
        tests:
          - not_null
      - name: latest_status_chg_time_jst
        description: "最終ステータス変更日時(JST)"
        tests:
          - not_null
          # - is_datetime

  - name: dwh_price_history
    description: "DWH層。価格履歴"
    columns:
      - name: base_date
        description: "価格基準日"
        tests:
          - not_null
      - name: ticker
        description: "ticker名"
        tests:
          - not_null
      - name: ohlc_type
        description: "価格種別(Open/High/Low/Close)"
        tests:
          - not_null
      - name: price
        description: "価格"
        # tests:
          # - not_null
      - name: fetch_time_jst
        description: "データ取得日時(JST)"
        tests:
          - not_null
  - name: dwh_daily_position
    description: "特定の日付時点でのポジション状況を集計したテーブル"
    columns:
      - name: account
        description: "口座名(gp_fund,yuitomaru..)"
        tests:
          - not_null
      - name: ticker
        description: "ticker名"
        tests:
          - not_null
      - name: position
        description: "保有数量.ロングのみなので、マイナスはないはず"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"
      - name: avg_buy_price
        description: "平均購入単価"
        tests:
          - not_null
      - name: net_position
        description: "ネットポジション.検算用.ロングのみなので、マイナスはないはず"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"
      - name: partition_date
        description: "基準日（パーティション用）"
        tests:
          - not_null

