version: 2

models:
  - name: dwh_asset_status_history
    description: "DWH層。RAW層で外部テーブルのアセットステータス変更履歴について型など変換している。"
    columns:
      - name: event_time_jst
        description: "ステータス変更日時(JST)"
        tests:
          - not_null
      - name: ticker
        description: "ticker名"
        tests:
          - not_null
      - name: is_monitor
        description: "モニタリング対象フラグ"
        tests:
          - not_null
      - name: is_watch
        description: "取引対象フラグ"
        tests:
          - not_null

  - name: dwh_trade_history
    description: "DWH層。RAW層で外部テーブルの取引履歴について型など変換している。"
    columns:
      - name: event_time_jst
        description: "レコード入力日時(JST)"
        tests:
          - not_null
      - name: trade_date
        description: "取引日(JST)"
        tests:
          - not_null
      - name: ticker
        description: "ticker名"
        tests:
          - not_null
      - name: trade_type
        description: "取引種別(buy or sell)"
        tests:
          - not_null
      - name: account
        description: "口座名(gp_fund,yuitomaru..)"
        tests:
          - not_null
      - name: order_count
        description: "取引口数"
        tests:
          - not_null
      - name: price
        description: "取引価格"
        tests:
          - not_null
      - name: memo
        description: "メモ"
        tests:
          - not_null

  - name: dwh_trade_history_with_cash
    description: "DWH層。各取引の裏のcashの移動レコードも含めた取引履歴。"
    columns:
      - name: event_time_jst
        description: "レコード入力日時(JST)"
        tests:
          - not_null
      - name: trade_date
        description: "取引日(JST)"
        tests:
          - not_null
      - name: ticker
        description: "ticker名"
        tests:
          - not_null
      - name: trade_type
        description: "取引種別(buy or sell)"
        tests:
          - not_null
      - name: account
        description: "口座名(gp_fund,yuitomaru..)"
        tests:
          - not_null
      - name: order_count
        description: "取引口数"
        tests:
          - not_null
      - name: price
        description: "取引価格"
        tests:
          - not_null
      - name: memo
        description: "メモ"
        tests:
          - not_null
