version: 2

seeds:
  - name: dim_summary_ticker_list
    description: "取引銘柄のマスターデータ。サマリー表示用の順序とアクティブ状態を管理"
    columns:
      - name: ticker
        description: "銘柄コード（例：^GSPC, BTC-USD）"
        tests:
          - not_null
          - unique
      - name: order_group
        description: "表示グループ番号（1:株価指数, 2:債券, 3:為替, 4:暗号資産, 5:個別株）"
        tests:
          - not_null
      - name: order_index
        description: "グループ内の表示順序"
        tests:
          - not_null
      - name: is_active_holiday
        description: "休日でも取引が行われるかどうか（TRUE:休日も取引, FALSE:平日のみ）"
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['true', 'false', 'TRUE', 'FALSE']