version: 2

models:
  - name: dm_position
    description: "特定の日付時点でのポジション状況を集計したテーブル"
    columns:
      - name: account
        description: "口座名(gp_fund,yuitomaru..)"
        tests:
          - not_null
      - name: ticker
        description: "ticker名"
        tests:
          - not_null
      - name: asset_type
        description: "アセット種別(株,金利..)"
      - name: asset_name
        description: "資産名"
      - name: position
        description: "保有数量.ロングのみなので、マイナスはないはず"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"
      - name: partition_date
        description: "基準日（パーティション用）"
        tests:
          - not_null
