name: Daily dbt run (dm_position)

on:
  schedule:
    # JST 07:00 → UTC 22:00
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-dbt:
    runs-on: ubuntu-latest
    env:
      DBT_PROFILES_DIR: .
      GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/sa.json
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dbt-bigquery
        run: pip install "dbt-bigquery==1.10.*"

      - name: Write SA key
        run: 'echo "$GCP_SA_KEY_JSON" > sa.json'
        env:
          GCP_SA_KEY_JSON: ${{ secrets.TERRAFORM_GCA_PROD }}

      - name: Run dbt (deps + run + test)
        run: |
          dbt deps
          dbt run  --target prod --select dwh_daily_position dm_daily_aum dm_daily_all_term_pl dm_daily_position_value
          dbt test --target prod --select dwh_daily_position dm_daily_aum dm_daily_all_term_pl dm_daily_position_value