name: dbt CI

on:
  pull_request:
    branches: [main, master]
    paths:
      - 'models/**'
      - 'macros/**'
      - 'tests/**'
      - 'seeds/**'
      - 'snapshots/**'
      - 'dbt_project.yml'
      - 'packages.yml'
      - 'profiles_ci.yml'
      - 'profiles.yml'

jobs:
  dbt-ci:
    runs-on: ubuntu-latest
    
    env:
      DBT_PROFILES_DIR: .
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Google Cloud credentials
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GOOGLE_CREDENTIALS" > keyfile.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/keyfile.json" >> $GITHUB_ENV

      - name: Use CI profiles
        run: |
          cp profiles_ci.yml profiles.yml

      - name: Install dbt packages
        run: dbt deps

      - name: Check dbt configuration
        run: dbt debug

      - name: Parse dbt project
        run: dbt parse

      - name: Run dbt models (dry-run)
        run: dbt run --target dev

      - name: Run dbt tests
        run: dbt test --target dev

      - name: Generate and upload docs
        run: |
          dbt docs generate --target dev
        if: success()
